package org.trump.vincent.ibatis.dal.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.trump.vincent.ibatis.dal.model.VideoTranscode;
import org.trump.vincent.ibatis.dal.model.VideoTranscodeExample;

public interface VideoTranscodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    long countByExample(VideoTranscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    int insert(VideoTranscode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    int insertSelective(VideoTranscode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    List<VideoTranscode> selectByExample(VideoTranscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VideoTranscode record, @Param("example") VideoTranscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VideoTranscode record, @Param("example") VideoTranscodeExample example);
}