package org.trump.vincent.ibatis.dal.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.trump.vincent.ibatis.dal.model.VideoReference;
import org.trump.vincent.ibatis.dal.model.VideoReferenceExample;

public interface VideoReferenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_reference
     *
     * @mbg.generated
     */
    long countByExample(VideoReferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_reference
     *
     * @mbg.generated
     */
    int insert(VideoReference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_reference
     *
     * @mbg.generated
     */
    int insertSelective(VideoReference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_reference
     *
     * @mbg.generated
     */
    List<VideoReference> selectByExample(VideoReferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_reference
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VideoReference record, @Param("example") VideoReferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_reference
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VideoReference record, @Param("example") VideoReferenceExample example);
}