package org.trump.vincent.ibatis.dal.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.trump.vincent.ibatis.dal.model.VideoMaterial;
import org.trump.vincent.ibatis.dal.model.VideoMaterialExample;

public interface VideoMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    long countByExample(VideoMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    int insert(VideoMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    int insertSelective(VideoMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    List<VideoMaterial> selectByExampleWithBLOBs(VideoMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    List<VideoMaterial> selectByExample(VideoMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VideoMaterial record, @Param("example") VideoMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") VideoMaterial record, @Param("example") VideoMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VideoMaterial record, @Param("example") VideoMaterialExample example);
}