package org.trump.vincent.ibatis.dal.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VideoTranscodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    public VideoTranscodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVideoidIsNull() {
            addCriterion("videoid is null");
            return (Criteria) this;
        }

        public Criteria andVideoidIsNotNull() {
            addCriterion("videoid is not null");
            return (Criteria) this;
        }

        public Criteria andVideoidEqualTo(Long value) {
            addCriterion("videoid =", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidNotEqualTo(Long value) {
            addCriterion("videoid <>", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidGreaterThan(Long value) {
            addCriterion("videoid >", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidGreaterThanOrEqualTo(Long value) {
            addCriterion("videoid >=", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidLessThan(Long value) {
            addCriterion("videoid <", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidLessThanOrEqualTo(Long value) {
            addCriterion("videoid <=", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidIn(List<Long> values) {
            addCriterion("videoid in", values, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidNotIn(List<Long> values) {
            addCriterion("videoid not in", values, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidBetween(Long value1, Long value2) {
            addCriterion("videoid between", value1, value2, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidNotBetween(Long value1, Long value2) {
            addCriterion("videoid not between", value1, value2, "videoid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andFormatIsNull() {
            addCriterion("format is null");
            return (Criteria) this;
        }

        public Criteria andFormatIsNotNull() {
            addCriterion("format is not null");
            return (Criteria) this;
        }

        public Criteria andFormatEqualTo(String value) {
            addCriterion("format =", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotEqualTo(String value) {
            addCriterion("format <>", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThan(String value) {
            addCriterion("format >", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThanOrEqualTo(String value) {
            addCriterion("format >=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThan(String value) {
            addCriterion("format <", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThanOrEqualTo(String value) {
            addCriterion("format <=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLike(String value) {
            addCriterion("format like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotLike(String value) {
            addCriterion("format not like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatIn(List<String> values) {
            addCriterion("format in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotIn(List<String> values) {
            addCriterion("format not in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatBetween(String value1, String value2) {
            addCriterion("format between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotBetween(String value1, String value2) {
            addCriterion("format not between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNull() {
            addCriterion("capacity is null");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNotNull() {
            addCriterion("capacity is not null");
            return (Criteria) this;
        }

        public Criteria andCapacityEqualTo(Double value) {
            addCriterion("capacity =", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotEqualTo(Double value) {
            addCriterion("capacity <>", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThan(Double value) {
            addCriterion("capacity >", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThanOrEqualTo(Double value) {
            addCriterion("capacity >=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThan(Double value) {
            addCriterion("capacity <", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThanOrEqualTo(Double value) {
            addCriterion("capacity <=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityIn(List<Double> values) {
            addCriterion("capacity in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotIn(List<Double> values) {
            addCriterion("capacity not in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityBetween(Double value1, Double value2) {
            addCriterion("capacity between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotBetween(Double value1, Double value2) {
            addCriterion("capacity not between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Integer> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Integer> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Integer value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Integer value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Integer value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Integer value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Integer value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Integer> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Integer> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Integer value1, Integer value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Integer value1, Integer value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andBitRateIsNull() {
            addCriterion("bit_rate is null");
            return (Criteria) this;
        }

        public Criteria andBitRateIsNotNull() {
            addCriterion("bit_rate is not null");
            return (Criteria) this;
        }

        public Criteria andBitRateEqualTo(Double value) {
            addCriterion("bit_rate =", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateNotEqualTo(Double value) {
            addCriterion("bit_rate <>", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateGreaterThan(Double value) {
            addCriterion("bit_rate >", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateGreaterThanOrEqualTo(Double value) {
            addCriterion("bit_rate >=", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateLessThan(Double value) {
            addCriterion("bit_rate <", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateLessThanOrEqualTo(Double value) {
            addCriterion("bit_rate <=", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateIn(List<Double> values) {
            addCriterion("bit_rate in", values, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateNotIn(List<Double> values) {
            addCriterion("bit_rate not in", values, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateBetween(Double value1, Double value2) {
            addCriterion("bit_rate between", value1, value2, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateNotBetween(Double value1, Double value2) {
            addCriterion("bit_rate not between", value1, value2, "bitRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateIsNull() {
            addCriterion("frame_rate is null");
            return (Criteria) this;
        }

        public Criteria andFrameRateIsNotNull() {
            addCriterion("frame_rate is not null");
            return (Criteria) this;
        }

        public Criteria andFrameRateEqualTo(Double value) {
            addCriterion("frame_rate =", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateNotEqualTo(Double value) {
            addCriterion("frame_rate <>", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateGreaterThan(Double value) {
            addCriterion("frame_rate >", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateGreaterThanOrEqualTo(Double value) {
            addCriterion("frame_rate >=", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateLessThan(Double value) {
            addCriterion("frame_rate <", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateLessThanOrEqualTo(Double value) {
            addCriterion("frame_rate <=", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateIn(List<Double> values) {
            addCriterion("frame_rate in", values, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateNotIn(List<Double> values) {
            addCriterion("frame_rate not in", values, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateBetween(Double value1, Double value2) {
            addCriterion("frame_rate between", value1, value2, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateNotBetween(Double value1, Double value2) {
            addCriterion("frame_rate not between", value1, value2, "frameRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateIsNull() {
            addCriterion("audio_rate is null");
            return (Criteria) this;
        }

        public Criteria andAudioRateIsNotNull() {
            addCriterion("audio_rate is not null");
            return (Criteria) this;
        }

        public Criteria andAudioRateEqualTo(Double value) {
            addCriterion("audio_rate =", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateNotEqualTo(Double value) {
            addCriterion("audio_rate <>", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateGreaterThan(Double value) {
            addCriterion("audio_rate >", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateGreaterThanOrEqualTo(Double value) {
            addCriterion("audio_rate >=", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateLessThan(Double value) {
            addCriterion("audio_rate <", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateLessThanOrEqualTo(Double value) {
            addCriterion("audio_rate <=", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateIn(List<Double> values) {
            addCriterion("audio_rate in", values, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateNotIn(List<Double> values) {
            addCriterion("audio_rate not in", values, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateBetween(Double value1, Double value2) {
            addCriterion("audio_rate between", value1, value2, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateNotBetween(Double value1, Double value2) {
            addCriterion("audio_rate not between", value1, value2, "audioRate");
            return (Criteria) this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("duration is null");
            return (Criteria) this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("duration is not null");
            return (Criteria) this;
        }

        public Criteria andDurationEqualTo(Integer value) {
            addCriterion("duration =", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotEqualTo(Integer value) {
            addCriterion("duration <>", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThan(Integer value) {
            addCriterion("duration >", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("duration >=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThan(Integer value) {
            addCriterion("duration <", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThanOrEqualTo(Integer value) {
            addCriterion("duration <=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationIn(List<Integer> values) {
            addCriterion("duration in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotIn(List<Integer> values) {
            addCriterion("duration not in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationBetween(Integer value1, Integer value2) {
            addCriterion("duration between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("duration not between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andThumbnailIsNull() {
            addCriterion("thumbnail is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailIsNotNull() {
            addCriterion("thumbnail is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailEqualTo(String value) {
            addCriterion("thumbnail =", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotEqualTo(String value) {
            addCriterion("thumbnail <>", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailGreaterThan(String value) {
            addCriterion("thumbnail >", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailGreaterThanOrEqualTo(String value) {
            addCriterion("thumbnail >=", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLessThan(String value) {
            addCriterion("thumbnail <", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLessThanOrEqualTo(String value) {
            addCriterion("thumbnail <=", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLike(String value) {
            addCriterion("thumbnail like", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotLike(String value) {
            addCriterion("thumbnail not like", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailIn(List<String> values) {
            addCriterion("thumbnail in", values, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotIn(List<String> values) {
            addCriterion("thumbnail not in", values, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailBetween(String value1, String value2) {
            addCriterion("thumbnail between", value1, value2, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotBetween(String value1, String value2) {
            addCriterion("thumbnail not between", value1, value2, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNull() {
            addCriterion("mod_time is null");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNotNull() {
            addCriterion("mod_time is not null");
            return (Criteria) this;
        }

        public Criteria andModTimeEqualTo(Date value) {
            addCriterion("mod_time =", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotEqualTo(Date value) {
            addCriterion("mod_time <>", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThan(Date value) {
            addCriterion("mod_time >", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mod_time >=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThan(Date value) {
            addCriterion("mod_time <", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThanOrEqualTo(Date value) {
            addCriterion("mod_time <=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIn(List<Date> values) {
            addCriterion("mod_time in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotIn(List<Date> values) {
            addCriterion("mod_time not in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeBetween(Date value1, Date value2) {
            addCriterion("mod_time between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotBetween(Date value1, Date value2) {
            addCriterion("mod_time not between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andTransferStatusIsNull() {
            addCriterion("transfer_status is null");
            return (Criteria) this;
        }

        public Criteria andTransferStatusIsNotNull() {
            addCriterion("transfer_status is not null");
            return (Criteria) this;
        }

        public Criteria andTransferStatusEqualTo(Byte value) {
            addCriterion("transfer_status =", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusNotEqualTo(Byte value) {
            addCriterion("transfer_status <>", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusGreaterThan(Byte value) {
            addCriterion("transfer_status >", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("transfer_status >=", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusLessThan(Byte value) {
            addCriterion("transfer_status <", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusLessThanOrEqualTo(Byte value) {
            addCriterion("transfer_status <=", value, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusIn(List<Byte> values) {
            addCriterion("transfer_status in", values, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusNotIn(List<Byte> values) {
            addCriterion("transfer_status not in", values, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusBetween(Byte value1, Byte value2) {
            addCriterion("transfer_status between", value1, value2, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("transfer_status not between", value1, value2, "transferStatus");
            return (Criteria) this;
        }

        public Criteria andTransferTimeIsNull() {
            addCriterion("transfer_time is null");
            return (Criteria) this;
        }

        public Criteria andTransferTimeIsNotNull() {
            addCriterion("transfer_time is not null");
            return (Criteria) this;
        }

        public Criteria andTransferTimeEqualTo(Date value) {
            addCriterion("transfer_time =", value, "transferTime");
            return (Criteria) this;
        }

        public Criteria andTransferTimeNotEqualTo(Date value) {
            addCriterion("transfer_time <>", value, "transferTime");
            return (Criteria) this;
        }

        public Criteria andTransferTimeGreaterThan(Date value) {
            addCriterion("transfer_time >", value, "transferTime");
            return (Criteria) this;
        }

        public Criteria andTransferTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("transfer_time >=", value, "transferTime");
            return (Criteria) this;
        }

        public Criteria andTransferTimeLessThan(Date value) {
            addCriterion("transfer_time <", value, "transferTime");
            return (Criteria) this;
        }

        public Criteria andTransferTimeLessThanOrEqualTo(Date value) {
            addCriterion("transfer_time <=", value, "transferTime");
            return (Criteria) this;
        }

        public Criteria andTransferTimeIn(List<Date> values) {
            addCriterion("transfer_time in", values, "transferTime");
            return (Criteria) this;
        }

        public Criteria andTransferTimeNotIn(List<Date> values) {
            addCriterion("transfer_time not in", values, "transferTime");
            return (Criteria) this;
        }

        public Criteria andTransferTimeBetween(Date value1, Date value2) {
            addCriterion("transfer_time between", value1, value2, "transferTime");
            return (Criteria) this;
        }

        public Criteria andTransferTimeNotBetween(Date value1, Date value2) {
            addCriterion("transfer_time not between", value1, value2, "transferTime");
            return (Criteria) this;
        }

        public Criteria andVideoCodecIsNull() {
            addCriterion("video_codec is null");
            return (Criteria) this;
        }

        public Criteria andVideoCodecIsNotNull() {
            addCriterion("video_codec is not null");
            return (Criteria) this;
        }

        public Criteria andVideoCodecEqualTo(String value) {
            addCriterion("video_codec =", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecNotEqualTo(String value) {
            addCriterion("video_codec <>", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecGreaterThan(String value) {
            addCriterion("video_codec >", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecGreaterThanOrEqualTo(String value) {
            addCriterion("video_codec >=", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecLessThan(String value) {
            addCriterion("video_codec <", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecLessThanOrEqualTo(String value) {
            addCriterion("video_codec <=", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecLike(String value) {
            addCriterion("video_codec like", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecNotLike(String value) {
            addCriterion("video_codec not like", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecIn(List<String> values) {
            addCriterion("video_codec in", values, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecNotIn(List<String> values) {
            addCriterion("video_codec not in", values, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecBetween(String value1, String value2) {
            addCriterion("video_codec between", value1, value2, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecNotBetween(String value1, String value2) {
            addCriterion("video_codec not between", value1, value2, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecIsNull() {
            addCriterion("audio_codec is null");
            return (Criteria) this;
        }

        public Criteria andAudioCodecIsNotNull() {
            addCriterion("audio_codec is not null");
            return (Criteria) this;
        }

        public Criteria andAudioCodecEqualTo(String value) {
            addCriterion("audio_codec =", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecNotEqualTo(String value) {
            addCriterion("audio_codec <>", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecGreaterThan(String value) {
            addCriterion("audio_codec >", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecGreaterThanOrEqualTo(String value) {
            addCriterion("audio_codec >=", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecLessThan(String value) {
            addCriterion("audio_codec <", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecLessThanOrEqualTo(String value) {
            addCriterion("audio_codec <=", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecLike(String value) {
            addCriterion("audio_codec like", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecNotLike(String value) {
            addCriterion("audio_codec not like", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecIn(List<String> values) {
            addCriterion("audio_codec in", values, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecNotIn(List<String> values) {
            addCriterion("audio_codec not in", values, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecBetween(String value1, String value2) {
            addCriterion("audio_codec between", value1, value2, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecNotBetween(String value1, String value2) {
            addCriterion("audio_codec not between", value1, value2, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andTransfermd5IsNull() {
            addCriterion("transferMd5 is null");
            return (Criteria) this;
        }

        public Criteria andTransfermd5IsNotNull() {
            addCriterion("transferMd5 is not null");
            return (Criteria) this;
        }

        public Criteria andTransfermd5EqualTo(String value) {
            addCriterion("transferMd5 =", value, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andTransfermd5NotEqualTo(String value) {
            addCriterion("transferMd5 <>", value, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andTransfermd5GreaterThan(String value) {
            addCriterion("transferMd5 >", value, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andTransfermd5GreaterThanOrEqualTo(String value) {
            addCriterion("transferMd5 >=", value, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andTransfermd5LessThan(String value) {
            addCriterion("transferMd5 <", value, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andTransfermd5LessThanOrEqualTo(String value) {
            addCriterion("transferMd5 <=", value, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andTransfermd5Like(String value) {
            addCriterion("transferMd5 like", value, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andTransfermd5NotLike(String value) {
            addCriterion("transferMd5 not like", value, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andTransfermd5In(List<String> values) {
            addCriterion("transferMd5 in", values, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andTransfermd5NotIn(List<String> values) {
            addCriterion("transferMd5 not in", values, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andTransfermd5Between(String value1, String value2) {
            addCriterion("transferMd5 between", value1, value2, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andTransfermd5NotBetween(String value1, String value2) {
            addCriterion("transferMd5 not between", value1, value2, "transfermd5");
            return (Criteria) this;
        }

        public Criteria andVideoRateIsNull() {
            addCriterion("video_rate is null");
            return (Criteria) this;
        }

        public Criteria andVideoRateIsNotNull() {
            addCriterion("video_rate is not null");
            return (Criteria) this;
        }

        public Criteria andVideoRateEqualTo(Double value) {
            addCriterion("video_rate =", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateNotEqualTo(Double value) {
            addCriterion("video_rate <>", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateGreaterThan(Double value) {
            addCriterion("video_rate >", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateGreaterThanOrEqualTo(Double value) {
            addCriterion("video_rate >=", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateLessThan(Double value) {
            addCriterion("video_rate <", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateLessThanOrEqualTo(Double value) {
            addCriterion("video_rate <=", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateIn(List<Double> values) {
            addCriterion("video_rate in", values, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateNotIn(List<Double> values) {
            addCriterion("video_rate not in", values, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateBetween(Double value1, Double value2) {
            addCriterion("video_rate between", value1, value2, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateNotBetween(Double value1, Double value2) {
            addCriterion("video_rate not between", value1, value2, "videoRate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_transfer
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_transfer
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}