package org.trump.vincent.ibatis.dal.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VideoMaterialExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_material
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_material
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_material
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    public VideoMaterialExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_material
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_material
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMaterialIdIsNull() {
            addCriterion("material_id is null");
            return (Criteria) this;
        }

        public Criteria andMaterialIdIsNotNull() {
            addCriterion("material_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialIdEqualTo(Long value) {
            addCriterion("material_id =", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotEqualTo(Long value) {
            addCriterion("material_id <>", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdGreaterThan(Long value) {
            addCriterion("material_id >", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdGreaterThanOrEqualTo(Long value) {
            addCriterion("material_id >=", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdLessThan(Long value) {
            addCriterion("material_id <", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdLessThanOrEqualTo(Long value) {
            addCriterion("material_id <=", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdIn(List<Long> values) {
            addCriterion("material_id in", values, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotIn(List<Long> values) {
            addCriterion("material_id not in", values, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdBetween(Long value1, Long value2) {
            addCriterion("material_id between", value1, value2, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotBetween(Long value1, Long value2) {
            addCriterion("material_id not between", value1, value2, "materialId");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andCampaignidIsNull() {
            addCriterion("campaignid is null");
            return (Criteria) this;
        }

        public Criteria andCampaignidIsNotNull() {
            addCriterion("campaignid is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignidEqualTo(Long value) {
            addCriterion("campaignid =", value, "campaignid");
            return (Criteria) this;
        }

        public Criteria andCampaignidNotEqualTo(Long value) {
            addCriterion("campaignid <>", value, "campaignid");
            return (Criteria) this;
        }

        public Criteria andCampaignidGreaterThan(Long value) {
            addCriterion("campaignid >", value, "campaignid");
            return (Criteria) this;
        }

        public Criteria andCampaignidGreaterThanOrEqualTo(Long value) {
            addCriterion("campaignid >=", value, "campaignid");
            return (Criteria) this;
        }

        public Criteria andCampaignidLessThan(Long value) {
            addCriterion("campaignid <", value, "campaignid");
            return (Criteria) this;
        }

        public Criteria andCampaignidLessThanOrEqualTo(Long value) {
            addCriterion("campaignid <=", value, "campaignid");
            return (Criteria) this;
        }

        public Criteria andCampaignidIn(List<Long> values) {
            addCriterion("campaignid in", values, "campaignid");
            return (Criteria) this;
        }

        public Criteria andCampaignidNotIn(List<Long> values) {
            addCriterion("campaignid not in", values, "campaignid");
            return (Criteria) this;
        }

        public Criteria andCampaignidBetween(Long value1, Long value2) {
            addCriterion("campaignid between", value1, value2, "campaignid");
            return (Criteria) this;
        }

        public Criteria andCampaignidNotBetween(Long value1, Long value2) {
            addCriterion("campaignid not between", value1, value2, "campaignid");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIsNull() {
            addCriterion("material_type is null");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIsNotNull() {
            addCriterion("material_type is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeEqualTo(Integer value) {
            addCriterion("material_type =", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeNotEqualTo(Integer value) {
            addCriterion("material_type <>", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeGreaterThan(Integer value) {
            addCriterion("material_type >", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_type >=", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeLessThan(Integer value) {
            addCriterion("material_type <", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeLessThanOrEqualTo(Integer value) {
            addCriterion("material_type <=", value, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeIn(List<Integer> values) {
            addCriterion("material_type in", values, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeNotIn(List<Integer> values) {
            addCriterion("material_type not in", values, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeBetween(Integer value1, Integer value2) {
            addCriterion("material_type between", value1, value2, "materialType");
            return (Criteria) this;
        }

        public Criteria andMaterialTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("material_type not between", value1, value2, "materialType");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNull() {
            addCriterion("isdel is null");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNotNull() {
            addCriterion("isdel is not null");
            return (Criteria) this;
        }

        public Criteria andIsdelEqualTo(Byte value) {
            addCriterion("isdel =", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotEqualTo(Byte value) {
            addCriterion("isdel <>", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThan(Byte value) {
            addCriterion("isdel >", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThanOrEqualTo(Byte value) {
            addCriterion("isdel >=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThan(Byte value) {
            addCriterion("isdel <", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThanOrEqualTo(Byte value) {
            addCriterion("isdel <=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelIn(List<Byte> values) {
            addCriterion("isdel in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotIn(List<Byte> values) {
            addCriterion("isdel not in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelBetween(Byte value1, Byte value2) {
            addCriterion("isdel between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotBetween(Byte value1, Byte value2) {
            addCriterion("isdel not between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andAuditUseridIsNull() {
            addCriterion("audit_userid is null");
            return (Criteria) this;
        }

        public Criteria andAuditUseridIsNotNull() {
            addCriterion("audit_userid is not null");
            return (Criteria) this;
        }

        public Criteria andAuditUseridEqualTo(Long value) {
            addCriterion("audit_userid =", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridNotEqualTo(Long value) {
            addCriterion("audit_userid <>", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridGreaterThan(Long value) {
            addCriterion("audit_userid >", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("audit_userid >=", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridLessThan(Long value) {
            addCriterion("audit_userid <", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridLessThanOrEqualTo(Long value) {
            addCriterion("audit_userid <=", value, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridIn(List<Long> values) {
            addCriterion("audit_userid in", values, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridNotIn(List<Long> values) {
            addCriterion("audit_userid not in", values, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridBetween(Long value1, Long value2) {
            addCriterion("audit_userid between", value1, value2, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditUseridNotBetween(Long value1, Long value2) {
            addCriterion("audit_userid not between", value1, value2, "auditUserid");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("audit_time is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("audit_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Date value) {
            addCriterion("audit_time =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Date value) {
            addCriterion("audit_time <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Date value) {
            addCriterion("audit_time >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("audit_time >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Date value) {
            addCriterion("audit_time <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("audit_time <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Date> values) {
            addCriterion("audit_time in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Date> values) {
            addCriterion("audit_time not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Date value1, Date value2) {
            addCriterion("audit_time between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("audit_time not between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(Byte value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(Byte value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(Byte value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(Byte value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Byte value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<Byte> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<Byte> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(Byte value1, Byte value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andReasonIdIsNull() {
            addCriterion("reason_id is null");
            return (Criteria) this;
        }

        public Criteria andReasonIdIsNotNull() {
            addCriterion("reason_id is not null");
            return (Criteria) this;
        }

        public Criteria andReasonIdEqualTo(Long value) {
            addCriterion("reason_id =", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdNotEqualTo(Long value) {
            addCriterion("reason_id <>", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdGreaterThan(Long value) {
            addCriterion("reason_id >", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdGreaterThanOrEqualTo(Long value) {
            addCriterion("reason_id >=", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdLessThan(Long value) {
            addCriterion("reason_id <", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdLessThanOrEqualTo(Long value) {
            addCriterion("reason_id <=", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdIn(List<Long> values) {
            addCriterion("reason_id in", values, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdNotIn(List<Long> values) {
            addCriterion("reason_id not in", values, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdBetween(Long value1, Long value2) {
            addCriterion("reason_id between", value1, value2, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdNotBetween(Long value1, Long value2) {
            addCriterion("reason_id not between", value1, value2, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonTextIsNull() {
            addCriterion("reason_text is null");
            return (Criteria) this;
        }

        public Criteria andReasonTextIsNotNull() {
            addCriterion("reason_text is not null");
            return (Criteria) this;
        }

        public Criteria andReasonTextEqualTo(String value) {
            addCriterion("reason_text =", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextNotEqualTo(String value) {
            addCriterion("reason_text <>", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextGreaterThan(String value) {
            addCriterion("reason_text >", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextGreaterThanOrEqualTo(String value) {
            addCriterion("reason_text >=", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextLessThan(String value) {
            addCriterion("reason_text <", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextLessThanOrEqualTo(String value) {
            addCriterion("reason_text <=", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextLike(String value) {
            addCriterion("reason_text like", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextNotLike(String value) {
            addCriterion("reason_text not like", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextIn(List<String> values) {
            addCriterion("reason_text in", values, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextNotIn(List<String> values) {
            addCriterion("reason_text not in", values, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextBetween(String value1, String value2) {
            addCriterion("reason_text between", value1, value2, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextNotBetween(String value1, String value2) {
            addCriterion("reason_text not between", value1, value2, "reasonText");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(Integer value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(Integer value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(Integer value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(Integer value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(Integer value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(Integer value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<Integer> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<Integer> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(Integer value1, Integer value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(Integer value1, Integer value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNull() {
            addCriterion("mod_time is null");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNotNull() {
            addCriterion("mod_time is not null");
            return (Criteria) this;
        }

        public Criteria andModTimeEqualTo(Date value) {
            addCriterion("mod_time =", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotEqualTo(Date value) {
            addCriterion("mod_time <>", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThan(Date value) {
            addCriterion("mod_time >", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mod_time >=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThan(Date value) {
            addCriterion("mod_time <", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThanOrEqualTo(Date value) {
            addCriterion("mod_time <=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIn(List<Date> values) {
            addCriterion("mod_time in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotIn(List<Date> values) {
            addCriterion("mod_time not in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeBetween(Date value1, Date value2) {
            addCriterion("mod_time between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotBetween(Date value1, Date value2) {
            addCriterion("mod_time not between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andDeluidIsNull() {
            addCriterion("deluid is null");
            return (Criteria) this;
        }

        public Criteria andDeluidIsNotNull() {
            addCriterion("deluid is not null");
            return (Criteria) this;
        }

        public Criteria andDeluidEqualTo(Long value) {
            addCriterion("deluid =", value, "deluid");
            return (Criteria) this;
        }

        public Criteria andDeluidNotEqualTo(Long value) {
            addCriterion("deluid <>", value, "deluid");
            return (Criteria) this;
        }

        public Criteria andDeluidGreaterThan(Long value) {
            addCriterion("deluid >", value, "deluid");
            return (Criteria) this;
        }

        public Criteria andDeluidGreaterThanOrEqualTo(Long value) {
            addCriterion("deluid >=", value, "deluid");
            return (Criteria) this;
        }

        public Criteria andDeluidLessThan(Long value) {
            addCriterion("deluid <", value, "deluid");
            return (Criteria) this;
        }

        public Criteria andDeluidLessThanOrEqualTo(Long value) {
            addCriterion("deluid <=", value, "deluid");
            return (Criteria) this;
        }

        public Criteria andDeluidIn(List<Long> values) {
            addCriterion("deluid in", values, "deluid");
            return (Criteria) this;
        }

        public Criteria andDeluidNotIn(List<Long> values) {
            addCriterion("deluid not in", values, "deluid");
            return (Criteria) this;
        }

        public Criteria andDeluidBetween(Long value1, Long value2) {
            addCriterion("deluid between", value1, value2, "deluid");
            return (Criteria) this;
        }

        public Criteria andDeluidNotBetween(Long value1, Long value2) {
            addCriterion("deluid not between", value1, value2, "deluid");
            return (Criteria) this;
        }

        public Criteria andOptidIsNull() {
            addCriterion("optid is null");
            return (Criteria) this;
        }

        public Criteria andOptidIsNotNull() {
            addCriterion("optid is not null");
            return (Criteria) this;
        }

        public Criteria andOptidEqualTo(Long value) {
            addCriterion("optid =", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidNotEqualTo(Long value) {
            addCriterion("optid <>", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidGreaterThan(Long value) {
            addCriterion("optid >", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidGreaterThanOrEqualTo(Long value) {
            addCriterion("optid >=", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidLessThan(Long value) {
            addCriterion("optid <", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidLessThanOrEqualTo(Long value) {
            addCriterion("optid <=", value, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidIn(List<Long> values) {
            addCriterion("optid in", values, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidNotIn(List<Long> values) {
            addCriterion("optid not in", values, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidBetween(Long value1, Long value2) {
            addCriterion("optid between", value1, value2, "optid");
            return (Criteria) this;
        }

        public Criteria andOptidNotBetween(Long value1, Long value2) {
            addCriterion("optid not between", value1, value2, "optid");
            return (Criteria) this;
        }

        public Criteria andAdgroupidIsNull() {
            addCriterion("adgroupid is null");
            return (Criteria) this;
        }

        public Criteria andAdgroupidIsNotNull() {
            addCriterion("adgroupid is not null");
            return (Criteria) this;
        }

        public Criteria andAdgroupidEqualTo(Long value) {
            addCriterion("adgroupid =", value, "adgroupid");
            return (Criteria) this;
        }

        public Criteria andAdgroupidNotEqualTo(Long value) {
            addCriterion("adgroupid <>", value, "adgroupid");
            return (Criteria) this;
        }

        public Criteria andAdgroupidGreaterThan(Long value) {
            addCriterion("adgroupid >", value, "adgroupid");
            return (Criteria) this;
        }

        public Criteria andAdgroupidGreaterThanOrEqualTo(Long value) {
            addCriterion("adgroupid >=", value, "adgroupid");
            return (Criteria) this;
        }

        public Criteria andAdgroupidLessThan(Long value) {
            addCriterion("adgroupid <", value, "adgroupid");
            return (Criteria) this;
        }

        public Criteria andAdgroupidLessThanOrEqualTo(Long value) {
            addCriterion("adgroupid <=", value, "adgroupid");
            return (Criteria) this;
        }

        public Criteria andAdgroupidIn(List<Long> values) {
            addCriterion("adgroupid in", values, "adgroupid");
            return (Criteria) this;
        }

        public Criteria andAdgroupidNotIn(List<Long> values) {
            addCriterion("adgroupid not in", values, "adgroupid");
            return (Criteria) this;
        }

        public Criteria andAdgroupidBetween(Long value1, Long value2) {
            addCriterion("adgroupid between", value1, value2, "adgroupid");
            return (Criteria) this;
        }

        public Criteria andAdgroupidNotBetween(Long value1, Long value2) {
            addCriterion("adgroupid not between", value1, value2, "adgroupid");
            return (Criteria) this;
        }

        public Criteria andPauseStatusIsNull() {
            addCriterion("pause_status is null");
            return (Criteria) this;
        }

        public Criteria andPauseStatusIsNotNull() {
            addCriterion("pause_status is not null");
            return (Criteria) this;
        }

        public Criteria andPauseStatusEqualTo(Byte value) {
            addCriterion("pause_status =", value, "pauseStatus");
            return (Criteria) this;
        }

        public Criteria andPauseStatusNotEqualTo(Byte value) {
            addCriterion("pause_status <>", value, "pauseStatus");
            return (Criteria) this;
        }

        public Criteria andPauseStatusGreaterThan(Byte value) {
            addCriterion("pause_status >", value, "pauseStatus");
            return (Criteria) this;
        }

        public Criteria andPauseStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("pause_status >=", value, "pauseStatus");
            return (Criteria) this;
        }

        public Criteria andPauseStatusLessThan(Byte value) {
            addCriterion("pause_status <", value, "pauseStatus");
            return (Criteria) this;
        }

        public Criteria andPauseStatusLessThanOrEqualTo(Byte value) {
            addCriterion("pause_status <=", value, "pauseStatus");
            return (Criteria) this;
        }

        public Criteria andPauseStatusIn(List<Byte> values) {
            addCriterion("pause_status in", values, "pauseStatus");
            return (Criteria) this;
        }

        public Criteria andPauseStatusNotIn(List<Byte> values) {
            addCriterion("pause_status not in", values, "pauseStatus");
            return (Criteria) this;
        }

        public Criteria andPauseStatusBetween(Byte value1, Byte value2) {
            addCriterion("pause_status between", value1, value2, "pauseStatus");
            return (Criteria) this;
        }

        public Criteria andPauseStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("pause_status not between", value1, value2, "pauseStatus");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIsNull() {
            addCriterion("video_type is null");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIsNotNull() {
            addCriterion("video_type is not null");
            return (Criteria) this;
        }

        public Criteria andVideoTypeEqualTo(Byte value) {
            addCriterion("video_type =", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotEqualTo(Byte value) {
            addCriterion("video_type <>", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeGreaterThan(Byte value) {
            addCriterion("video_type >", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("video_type >=", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeLessThan(Byte value) {
            addCriterion("video_type <", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeLessThanOrEqualTo(Byte value) {
            addCriterion("video_type <=", value, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeIn(List<Byte> values) {
            addCriterion("video_type in", values, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotIn(List<Byte> values) {
            addCriterion("video_type not in", values, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeBetween(Byte value1, Byte value2) {
            addCriterion("video_type between", value1, value2, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("video_type not between", value1, value2, "videoType");
            return (Criteria) this;
        }

        public Criteria andVideoCountIsNull() {
            addCriterion("video_count is null");
            return (Criteria) this;
        }

        public Criteria andVideoCountIsNotNull() {
            addCriterion("video_count is not null");
            return (Criteria) this;
        }

        public Criteria andVideoCountEqualTo(Integer value) {
            addCriterion("video_count =", value, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountNotEqualTo(Integer value) {
            addCriterion("video_count <>", value, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountGreaterThan(Integer value) {
            addCriterion("video_count >", value, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("video_count >=", value, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountLessThan(Integer value) {
            addCriterion("video_count <", value, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountLessThanOrEqualTo(Integer value) {
            addCriterion("video_count <=", value, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountIn(List<Integer> values) {
            addCriterion("video_count in", values, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountNotIn(List<Integer> values) {
            addCriterion("video_count not in", values, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountBetween(Integer value1, Integer value2) {
            addCriterion("video_count between", value1, value2, "videoCount");
            return (Criteria) this;
        }

        public Criteria andVideoCountNotBetween(Integer value1, Integer value2) {
            addCriterion("video_count not between", value1, value2, "videoCount");
            return (Criteria) this;
        }

        public Criteria andPicCountIsNull() {
            addCriterion("pic_count is null");
            return (Criteria) this;
        }

        public Criteria andPicCountIsNotNull() {
            addCriterion("pic_count is not null");
            return (Criteria) this;
        }

        public Criteria andPicCountEqualTo(Integer value) {
            addCriterion("pic_count =", value, "picCount");
            return (Criteria) this;
        }

        public Criteria andPicCountNotEqualTo(Integer value) {
            addCriterion("pic_count <>", value, "picCount");
            return (Criteria) this;
        }

        public Criteria andPicCountGreaterThan(Integer value) {
            addCriterion("pic_count >", value, "picCount");
            return (Criteria) this;
        }

        public Criteria andPicCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("pic_count >=", value, "picCount");
            return (Criteria) this;
        }

        public Criteria andPicCountLessThan(Integer value) {
            addCriterion("pic_count <", value, "picCount");
            return (Criteria) this;
        }

        public Criteria andPicCountLessThanOrEqualTo(Integer value) {
            addCriterion("pic_count <=", value, "picCount");
            return (Criteria) this;
        }

        public Criteria andPicCountIn(List<Integer> values) {
            addCriterion("pic_count in", values, "picCount");
            return (Criteria) this;
        }

        public Criteria andPicCountNotIn(List<Integer> values) {
            addCriterion("pic_count not in", values, "picCount");
            return (Criteria) this;
        }

        public Criteria andPicCountBetween(Integer value1, Integer value2) {
            addCriterion("pic_count between", value1, value2, "picCount");
            return (Criteria) this;
        }

        public Criteria andPicCountNotBetween(Integer value1, Integer value2) {
            addCriterion("pic_count not between", value1, value2, "picCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_material
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_material
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}