package org.trump.vincent.ibatis.dal.model;

import java.io.Serializable;
import java.util.Date;

public class Video implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.videoid
     *
     * @mbg.generated
     */
    private Long videoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.userid
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_name
     *
     * @mbg.generated
     */
    private String videoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.url_hash
     *
     * @mbg.generated
     */
    private Long urlHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_md5
     *
     * @mbg.generated
     */
    private String videoMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_content_md5
     *
     * @mbg.generated
     */
    private String videoContentMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.audit_content
     *
     * @mbg.generated
     */
    private String auditContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.source
     *
     * @mbg.generated
     */
    private Byte source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.format
     *
     * @mbg.generated
     */
    private String format;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.capacity
     *
     * @mbg.generated
     */
    private Double capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.width
     *
     * @mbg.generated
     */
    private Integer width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.bit_rate
     *
     * @mbg.generated
     */
    private Double bitRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.frame_rate
     *
     * @mbg.generated
     */
    private Double frameRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.audio_rate
     *
     * @mbg.generated
     */
    private Double audioRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.thumbnail
     *
     * @mbg.generated
     */
    private String thumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.isdel
     *
     * @mbg.generated
     */
    private Byte isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.mod_time
     *
     * @mbg.generated
     */
    private Date modTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.audit_status
     *
     * @mbg.generated
     */
    private Byte auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.audit_user_id
     *
     * @mbg.generated
     */
    private Long auditUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.audit_time
     *
     * @mbg.generated
     */
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.rsnid
     *
     * @mbg.generated
     */
    private Long rsnid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.reason_text
     *
     * @mbg.generated
     */
    private String reasonText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.robot_status
     *
     * @mbg.generated
     */
    private Byte robotStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.robot_reason
     *
     * @mbg.generated
     */
    private String robotReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.upload_status
     *
     * @mbg.generated
     */
    private Byte uploadStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.upload_id
     *
     * @mbg.generated
     */
    private String uploadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.outer_url
     *
     * @mbg.generated
     */
    private String outerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_codec
     *
     * @mbg.generated
     */
    private String videoCodec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.audio_codec
     *
     * @mbg.generated
     */
    private String audioCodec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_rate
     *
     * @mbg.generated
     */
    private Double videoRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.preview_url
     *
     * @mbg.generated
     */
    private String previewUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.videoid
     *
     * @return the value of video.videoid
     *
     * @mbg.generated
     */
    public Long getVideoid() {
        return videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.videoid
     *
     * @param videoid the value for video.videoid
     *
     * @mbg.generated
     */
    public void setVideoid(Long videoid) {
        this.videoid = videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.userid
     *
     * @return the value of video.userid
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.userid
     *
     * @param userid the value for video.userid
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_name
     *
     * @return the value of video.video_name
     *
     * @mbg.generated
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_name
     *
     * @param videoName the value for video.video_name
     *
     * @mbg.generated
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.url
     *
     * @return the value of video.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.url
     *
     * @param url the value for video.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.url_hash
     *
     * @return the value of video.url_hash
     *
     * @mbg.generated
     */
    public Long getUrlHash() {
        return urlHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.url_hash
     *
     * @param urlHash the value for video.url_hash
     *
     * @mbg.generated
     */
    public void setUrlHash(Long urlHash) {
        this.urlHash = urlHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_md5
     *
     * @return the value of video.video_md5
     *
     * @mbg.generated
     */
    public String getVideoMd5() {
        return videoMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_md5
     *
     * @param videoMd5 the value for video.video_md5
     *
     * @mbg.generated
     */
    public void setVideoMd5(String videoMd5) {
        this.videoMd5 = videoMd5 == null ? null : videoMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.content
     *
     * @return the value of video.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.content
     *
     * @param content the value for video.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_content_md5
     *
     * @return the value of video.video_content_md5
     *
     * @mbg.generated
     */
    public String getVideoContentMd5() {
        return videoContentMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_content_md5
     *
     * @param videoContentMd5 the value for video.video_content_md5
     *
     * @mbg.generated
     */
    public void setVideoContentMd5(String videoContentMd5) {
        this.videoContentMd5 = videoContentMd5 == null ? null : videoContentMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.audit_content
     *
     * @return the value of video.audit_content
     *
     * @mbg.generated
     */
    public String getAuditContent() {
        return auditContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.audit_content
     *
     * @param auditContent the value for video.audit_content
     *
     * @mbg.generated
     */
    public void setAuditContent(String auditContent) {
        this.auditContent = auditContent == null ? null : auditContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.source
     *
     * @return the value of video.source
     *
     * @mbg.generated
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.source
     *
     * @param source the value for video.source
     *
     * @mbg.generated
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.format
     *
     * @return the value of video.format
     *
     * @mbg.generated
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.format
     *
     * @param format the value for video.format
     *
     * @mbg.generated
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.capacity
     *
     * @return the value of video.capacity
     *
     * @mbg.generated
     */
    public Double getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.capacity
     *
     * @param capacity the value for video.capacity
     *
     * @mbg.generated
     */
    public void setCapacity(Double capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.height
     *
     * @return the value of video.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.height
     *
     * @param height the value for video.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.width
     *
     * @return the value of video.width
     *
     * @mbg.generated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.width
     *
     * @param width the value for video.width
     *
     * @mbg.generated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.bit_rate
     *
     * @return the value of video.bit_rate
     *
     * @mbg.generated
     */
    public Double getBitRate() {
        return bitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.bit_rate
     *
     * @param bitRate the value for video.bit_rate
     *
     * @mbg.generated
     */
    public void setBitRate(Double bitRate) {
        this.bitRate = bitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.frame_rate
     *
     * @return the value of video.frame_rate
     *
     * @mbg.generated
     */
    public Double getFrameRate() {
        return frameRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.frame_rate
     *
     * @param frameRate the value for video.frame_rate
     *
     * @mbg.generated
     */
    public void setFrameRate(Double frameRate) {
        this.frameRate = frameRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.audio_rate
     *
     * @return the value of video.audio_rate
     *
     * @mbg.generated
     */
    public Double getAudioRate() {
        return audioRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.audio_rate
     *
     * @param audioRate the value for video.audio_rate
     *
     * @mbg.generated
     */
    public void setAudioRate(Double audioRate) {
        this.audioRate = audioRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.duration
     *
     * @return the value of video.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.duration
     *
     * @param duration the value for video.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.thumbnail
     *
     * @return the value of video.thumbnail
     *
     * @mbg.generated
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.thumbnail
     *
     * @param thumbnail the value for video.thumbnail
     *
     * @mbg.generated
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.isdel
     *
     * @return the value of video.isdel
     *
     * @mbg.generated
     */
    public Byte getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.isdel
     *
     * @param isdel the value for video.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Byte isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.add_time
     *
     * @return the value of video.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.add_time
     *
     * @param addTime the value for video.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.mod_time
     *
     * @return the value of video.mod_time
     *
     * @mbg.generated
     */
    public Date getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.mod_time
     *
     * @param modTime the value for video.mod_time
     *
     * @mbg.generated
     */
    public void setModTime(Date modTime) {
        this.modTime = modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.audit_status
     *
     * @return the value of video.audit_status
     *
     * @mbg.generated
     */
    public Byte getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.audit_status
     *
     * @param auditStatus the value for video.audit_status
     *
     * @mbg.generated
     */
    public void setAuditStatus(Byte auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.audit_user_id
     *
     * @return the value of video.audit_user_id
     *
     * @mbg.generated
     */
    public Long getAuditUserId() {
        return auditUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.audit_user_id
     *
     * @param auditUserId the value for video.audit_user_id
     *
     * @mbg.generated
     */
    public void setAuditUserId(Long auditUserId) {
        this.auditUserId = auditUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.audit_time
     *
     * @return the value of video.audit_time
     *
     * @mbg.generated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.audit_time
     *
     * @param auditTime the value for video.audit_time
     *
     * @mbg.generated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.rsnid
     *
     * @return the value of video.rsnid
     *
     * @mbg.generated
     */
    public Long getRsnid() {
        return rsnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.rsnid
     *
     * @param rsnid the value for video.rsnid
     *
     * @mbg.generated
     */
    public void setRsnid(Long rsnid) {
        this.rsnid = rsnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.reason_text
     *
     * @return the value of video.reason_text
     *
     * @mbg.generated
     */
    public String getReasonText() {
        return reasonText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.reason_text
     *
     * @param reasonText the value for video.reason_text
     *
     * @mbg.generated
     */
    public void setReasonText(String reasonText) {
        this.reasonText = reasonText == null ? null : reasonText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.robot_status
     *
     * @return the value of video.robot_status
     *
     * @mbg.generated
     */
    public Byte getRobotStatus() {
        return robotStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.robot_status
     *
     * @param robotStatus the value for video.robot_status
     *
     * @mbg.generated
     */
    public void setRobotStatus(Byte robotStatus) {
        this.robotStatus = robotStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.robot_reason
     *
     * @return the value of video.robot_reason
     *
     * @mbg.generated
     */
    public String getRobotReason() {
        return robotReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.robot_reason
     *
     * @param robotReason the value for video.robot_reason
     *
     * @mbg.generated
     */
    public void setRobotReason(String robotReason) {
        this.robotReason = robotReason == null ? null : robotReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.upload_status
     *
     * @return the value of video.upload_status
     *
     * @mbg.generated
     */
    public Byte getUploadStatus() {
        return uploadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.upload_status
     *
     * @param uploadStatus the value for video.upload_status
     *
     * @mbg.generated
     */
    public void setUploadStatus(Byte uploadStatus) {
        this.uploadStatus = uploadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.upload_id
     *
     * @return the value of video.upload_id
     *
     * @mbg.generated
     */
    public String getUploadId() {
        return uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.upload_id
     *
     * @param uploadId the value for video.upload_id
     *
     * @mbg.generated
     */
    public void setUploadId(String uploadId) {
        this.uploadId = uploadId == null ? null : uploadId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.outer_url
     *
     * @return the value of video.outer_url
     *
     * @mbg.generated
     */
    public String getOuterUrl() {
        return outerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.outer_url
     *
     * @param outerUrl the value for video.outer_url
     *
     * @mbg.generated
     */
    public void setOuterUrl(String outerUrl) {
        this.outerUrl = outerUrl == null ? null : outerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.version
     *
     * @return the value of video.version
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.version
     *
     * @param version the value for video.version
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_codec
     *
     * @return the value of video.video_codec
     *
     * @mbg.generated
     */
    public String getVideoCodec() {
        return videoCodec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_codec
     *
     * @param videoCodec the value for video.video_codec
     *
     * @mbg.generated
     */
    public void setVideoCodec(String videoCodec) {
        this.videoCodec = videoCodec == null ? null : videoCodec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.audio_codec
     *
     * @return the value of video.audio_codec
     *
     * @mbg.generated
     */
    public String getAudioCodec() {
        return audioCodec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.audio_codec
     *
     * @param audioCodec the value for video.audio_codec
     *
     * @mbg.generated
     */
    public void setAudioCodec(String audioCodec) {
        this.audioCodec = audioCodec == null ? null : audioCodec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_rate
     *
     * @return the value of video.video_rate
     *
     * @mbg.generated
     */
    public Double getVideoRate() {
        return videoRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_rate
     *
     * @param videoRate the value for video.video_rate
     *
     * @mbg.generated
     */
    public void setVideoRate(Double videoRate) {
        this.videoRate = videoRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.preview_url
     *
     * @return the value of video.preview_url
     *
     * @mbg.generated
     */
    public String getPreviewUrl() {
        return previewUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.preview_url
     *
     * @param previewUrl the value for video.preview_url
     *
     * @mbg.generated
     */
    public void setPreviewUrl(String previewUrl) {
        this.previewUrl = previewUrl == null ? null : previewUrl.trim();
    }
}