package org.trump.vincent.ibatis.dal.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VideoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    public VideoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVideoidIsNull() {
            addCriterion("videoid is null");
            return (Criteria) this;
        }

        public Criteria andVideoidIsNotNull() {
            addCriterion("videoid is not null");
            return (Criteria) this;
        }

        public Criteria andVideoidEqualTo(Long value) {
            addCriterion("videoid =", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidNotEqualTo(Long value) {
            addCriterion("videoid <>", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidGreaterThan(Long value) {
            addCriterion("videoid >", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidGreaterThanOrEqualTo(Long value) {
            addCriterion("videoid >=", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidLessThan(Long value) {
            addCriterion("videoid <", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidLessThanOrEqualTo(Long value) {
            addCriterion("videoid <=", value, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidIn(List<Long> values) {
            addCriterion("videoid in", values, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidNotIn(List<Long> values) {
            addCriterion("videoid not in", values, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidBetween(Long value1, Long value2) {
            addCriterion("videoid between", value1, value2, "videoid");
            return (Criteria) this;
        }

        public Criteria andVideoidNotBetween(Long value1, Long value2) {
            addCriterion("videoid not between", value1, value2, "videoid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNull() {
            addCriterion("video_name is null");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNotNull() {
            addCriterion("video_name is not null");
            return (Criteria) this;
        }

        public Criteria andVideoNameEqualTo(String value) {
            addCriterion("video_name =", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotEqualTo(String value) {
            addCriterion("video_name <>", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThan(String value) {
            addCriterion("video_name >", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThanOrEqualTo(String value) {
            addCriterion("video_name >=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThan(String value) {
            addCriterion("video_name <", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThanOrEqualTo(String value) {
            addCriterion("video_name <=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLike(String value) {
            addCriterion("video_name like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotLike(String value) {
            addCriterion("video_name not like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameIn(List<String> values) {
            addCriterion("video_name in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotIn(List<String> values) {
            addCriterion("video_name not in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameBetween(String value1, String value2) {
            addCriterion("video_name between", value1, value2, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotBetween(String value1, String value2) {
            addCriterion("video_name not between", value1, value2, "videoName");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlHashIsNull() {
            addCriterion("url_hash is null");
            return (Criteria) this;
        }

        public Criteria andUrlHashIsNotNull() {
            addCriterion("url_hash is not null");
            return (Criteria) this;
        }

        public Criteria andUrlHashEqualTo(Long value) {
            addCriterion("url_hash =", value, "urlHash");
            return (Criteria) this;
        }

        public Criteria andUrlHashNotEqualTo(Long value) {
            addCriterion("url_hash <>", value, "urlHash");
            return (Criteria) this;
        }

        public Criteria andUrlHashGreaterThan(Long value) {
            addCriterion("url_hash >", value, "urlHash");
            return (Criteria) this;
        }

        public Criteria andUrlHashGreaterThanOrEqualTo(Long value) {
            addCriterion("url_hash >=", value, "urlHash");
            return (Criteria) this;
        }

        public Criteria andUrlHashLessThan(Long value) {
            addCriterion("url_hash <", value, "urlHash");
            return (Criteria) this;
        }

        public Criteria andUrlHashLessThanOrEqualTo(Long value) {
            addCriterion("url_hash <=", value, "urlHash");
            return (Criteria) this;
        }

        public Criteria andUrlHashIn(List<Long> values) {
            addCriterion("url_hash in", values, "urlHash");
            return (Criteria) this;
        }

        public Criteria andUrlHashNotIn(List<Long> values) {
            addCriterion("url_hash not in", values, "urlHash");
            return (Criteria) this;
        }

        public Criteria andUrlHashBetween(Long value1, Long value2) {
            addCriterion("url_hash between", value1, value2, "urlHash");
            return (Criteria) this;
        }

        public Criteria andUrlHashNotBetween(Long value1, Long value2) {
            addCriterion("url_hash not between", value1, value2, "urlHash");
            return (Criteria) this;
        }

        public Criteria andVideoMd5IsNull() {
            addCriterion("video_md5 is null");
            return (Criteria) this;
        }

        public Criteria andVideoMd5IsNotNull() {
            addCriterion("video_md5 is not null");
            return (Criteria) this;
        }

        public Criteria andVideoMd5EqualTo(String value) {
            addCriterion("video_md5 =", value, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andVideoMd5NotEqualTo(String value) {
            addCriterion("video_md5 <>", value, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andVideoMd5GreaterThan(String value) {
            addCriterion("video_md5 >", value, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andVideoMd5GreaterThanOrEqualTo(String value) {
            addCriterion("video_md5 >=", value, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andVideoMd5LessThan(String value) {
            addCriterion("video_md5 <", value, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andVideoMd5LessThanOrEqualTo(String value) {
            addCriterion("video_md5 <=", value, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andVideoMd5Like(String value) {
            addCriterion("video_md5 like", value, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andVideoMd5NotLike(String value) {
            addCriterion("video_md5 not like", value, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andVideoMd5In(List<String> values) {
            addCriterion("video_md5 in", values, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andVideoMd5NotIn(List<String> values) {
            addCriterion("video_md5 not in", values, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andVideoMd5Between(String value1, String value2) {
            addCriterion("video_md5 between", value1, value2, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andVideoMd5NotBetween(String value1, String value2) {
            addCriterion("video_md5 not between", value1, value2, "videoMd5");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5IsNull() {
            addCriterion("video_content_md5 is null");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5IsNotNull() {
            addCriterion("video_content_md5 is not null");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5EqualTo(String value) {
            addCriterion("video_content_md5 =", value, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5NotEqualTo(String value) {
            addCriterion("video_content_md5 <>", value, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5GreaterThan(String value) {
            addCriterion("video_content_md5 >", value, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5GreaterThanOrEqualTo(String value) {
            addCriterion("video_content_md5 >=", value, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5LessThan(String value) {
            addCriterion("video_content_md5 <", value, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5LessThanOrEqualTo(String value) {
            addCriterion("video_content_md5 <=", value, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5Like(String value) {
            addCriterion("video_content_md5 like", value, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5NotLike(String value) {
            addCriterion("video_content_md5 not like", value, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5In(List<String> values) {
            addCriterion("video_content_md5 in", values, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5NotIn(List<String> values) {
            addCriterion("video_content_md5 not in", values, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5Between(String value1, String value2) {
            addCriterion("video_content_md5 between", value1, value2, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andVideoContentMd5NotBetween(String value1, String value2) {
            addCriterion("video_content_md5 not between", value1, value2, "videoContentMd5");
            return (Criteria) this;
        }

        public Criteria andAuditContentIsNull() {
            addCriterion("audit_content is null");
            return (Criteria) this;
        }

        public Criteria andAuditContentIsNotNull() {
            addCriterion("audit_content is not null");
            return (Criteria) this;
        }

        public Criteria andAuditContentEqualTo(String value) {
            addCriterion("audit_content =", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentNotEqualTo(String value) {
            addCriterion("audit_content <>", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentGreaterThan(String value) {
            addCriterion("audit_content >", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentGreaterThanOrEqualTo(String value) {
            addCriterion("audit_content >=", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentLessThan(String value) {
            addCriterion("audit_content <", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentLessThanOrEqualTo(String value) {
            addCriterion("audit_content <=", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentLike(String value) {
            addCriterion("audit_content like", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentNotLike(String value) {
            addCriterion("audit_content not like", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentIn(List<String> values) {
            addCriterion("audit_content in", values, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentNotIn(List<String> values) {
            addCriterion("audit_content not in", values, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentBetween(String value1, String value2) {
            addCriterion("audit_content between", value1, value2, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentNotBetween(String value1, String value2) {
            addCriterion("audit_content not between", value1, value2, "auditContent");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(Byte value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(Byte value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(Byte value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(Byte value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(Byte value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(Byte value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<Byte> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<Byte> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(Byte value1, Byte value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(Byte value1, Byte value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andFormatIsNull() {
            addCriterion("format is null");
            return (Criteria) this;
        }

        public Criteria andFormatIsNotNull() {
            addCriterion("format is not null");
            return (Criteria) this;
        }

        public Criteria andFormatEqualTo(String value) {
            addCriterion("format =", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotEqualTo(String value) {
            addCriterion("format <>", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThan(String value) {
            addCriterion("format >", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThanOrEqualTo(String value) {
            addCriterion("format >=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThan(String value) {
            addCriterion("format <", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThanOrEqualTo(String value) {
            addCriterion("format <=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLike(String value) {
            addCriterion("format like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotLike(String value) {
            addCriterion("format not like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatIn(List<String> values) {
            addCriterion("format in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotIn(List<String> values) {
            addCriterion("format not in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatBetween(String value1, String value2) {
            addCriterion("format between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotBetween(String value1, String value2) {
            addCriterion("format not between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNull() {
            addCriterion("capacity is null");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNotNull() {
            addCriterion("capacity is not null");
            return (Criteria) this;
        }

        public Criteria andCapacityEqualTo(Double value) {
            addCriterion("capacity =", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotEqualTo(Double value) {
            addCriterion("capacity <>", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThan(Double value) {
            addCriterion("capacity >", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThanOrEqualTo(Double value) {
            addCriterion("capacity >=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThan(Double value) {
            addCriterion("capacity <", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThanOrEqualTo(Double value) {
            addCriterion("capacity <=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityIn(List<Double> values) {
            addCriterion("capacity in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotIn(List<Double> values) {
            addCriterion("capacity not in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityBetween(Double value1, Double value2) {
            addCriterion("capacity between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotBetween(Double value1, Double value2) {
            addCriterion("capacity not between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Integer> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Integer> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Integer value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Integer value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Integer value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Integer value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Integer value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Integer> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Integer> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Integer value1, Integer value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Integer value1, Integer value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andBitRateIsNull() {
            addCriterion("bit_rate is null");
            return (Criteria) this;
        }

        public Criteria andBitRateIsNotNull() {
            addCriterion("bit_rate is not null");
            return (Criteria) this;
        }

        public Criteria andBitRateEqualTo(Double value) {
            addCriterion("bit_rate =", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateNotEqualTo(Double value) {
            addCriterion("bit_rate <>", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateGreaterThan(Double value) {
            addCriterion("bit_rate >", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateGreaterThanOrEqualTo(Double value) {
            addCriterion("bit_rate >=", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateLessThan(Double value) {
            addCriterion("bit_rate <", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateLessThanOrEqualTo(Double value) {
            addCriterion("bit_rate <=", value, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateIn(List<Double> values) {
            addCriterion("bit_rate in", values, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateNotIn(List<Double> values) {
            addCriterion("bit_rate not in", values, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateBetween(Double value1, Double value2) {
            addCriterion("bit_rate between", value1, value2, "bitRate");
            return (Criteria) this;
        }

        public Criteria andBitRateNotBetween(Double value1, Double value2) {
            addCriterion("bit_rate not between", value1, value2, "bitRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateIsNull() {
            addCriterion("frame_rate is null");
            return (Criteria) this;
        }

        public Criteria andFrameRateIsNotNull() {
            addCriterion("frame_rate is not null");
            return (Criteria) this;
        }

        public Criteria andFrameRateEqualTo(Double value) {
            addCriterion("frame_rate =", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateNotEqualTo(Double value) {
            addCriterion("frame_rate <>", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateGreaterThan(Double value) {
            addCriterion("frame_rate >", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateGreaterThanOrEqualTo(Double value) {
            addCriterion("frame_rate >=", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateLessThan(Double value) {
            addCriterion("frame_rate <", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateLessThanOrEqualTo(Double value) {
            addCriterion("frame_rate <=", value, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateIn(List<Double> values) {
            addCriterion("frame_rate in", values, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateNotIn(List<Double> values) {
            addCriterion("frame_rate not in", values, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateBetween(Double value1, Double value2) {
            addCriterion("frame_rate between", value1, value2, "frameRate");
            return (Criteria) this;
        }

        public Criteria andFrameRateNotBetween(Double value1, Double value2) {
            addCriterion("frame_rate not between", value1, value2, "frameRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateIsNull() {
            addCriterion("audio_rate is null");
            return (Criteria) this;
        }

        public Criteria andAudioRateIsNotNull() {
            addCriterion("audio_rate is not null");
            return (Criteria) this;
        }

        public Criteria andAudioRateEqualTo(Double value) {
            addCriterion("audio_rate =", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateNotEqualTo(Double value) {
            addCriterion("audio_rate <>", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateGreaterThan(Double value) {
            addCriterion("audio_rate >", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateGreaterThanOrEqualTo(Double value) {
            addCriterion("audio_rate >=", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateLessThan(Double value) {
            addCriterion("audio_rate <", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateLessThanOrEqualTo(Double value) {
            addCriterion("audio_rate <=", value, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateIn(List<Double> values) {
            addCriterion("audio_rate in", values, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateNotIn(List<Double> values) {
            addCriterion("audio_rate not in", values, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateBetween(Double value1, Double value2) {
            addCriterion("audio_rate between", value1, value2, "audioRate");
            return (Criteria) this;
        }

        public Criteria andAudioRateNotBetween(Double value1, Double value2) {
            addCriterion("audio_rate not between", value1, value2, "audioRate");
            return (Criteria) this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("duration is null");
            return (Criteria) this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("duration is not null");
            return (Criteria) this;
        }

        public Criteria andDurationEqualTo(Integer value) {
            addCriterion("duration =", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotEqualTo(Integer value) {
            addCriterion("duration <>", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThan(Integer value) {
            addCriterion("duration >", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("duration >=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThan(Integer value) {
            addCriterion("duration <", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThanOrEqualTo(Integer value) {
            addCriterion("duration <=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationIn(List<Integer> values) {
            addCriterion("duration in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotIn(List<Integer> values) {
            addCriterion("duration not in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationBetween(Integer value1, Integer value2) {
            addCriterion("duration between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("duration not between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andThumbnailIsNull() {
            addCriterion("thumbnail is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailIsNotNull() {
            addCriterion("thumbnail is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailEqualTo(String value) {
            addCriterion("thumbnail =", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotEqualTo(String value) {
            addCriterion("thumbnail <>", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailGreaterThan(String value) {
            addCriterion("thumbnail >", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailGreaterThanOrEqualTo(String value) {
            addCriterion("thumbnail >=", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLessThan(String value) {
            addCriterion("thumbnail <", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLessThanOrEqualTo(String value) {
            addCriterion("thumbnail <=", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLike(String value) {
            addCriterion("thumbnail like", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotLike(String value) {
            addCriterion("thumbnail not like", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailIn(List<String> values) {
            addCriterion("thumbnail in", values, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotIn(List<String> values) {
            addCriterion("thumbnail not in", values, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailBetween(String value1, String value2) {
            addCriterion("thumbnail between", value1, value2, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotBetween(String value1, String value2) {
            addCriterion("thumbnail not between", value1, value2, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNull() {
            addCriterion("isdel is null");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNotNull() {
            addCriterion("isdel is not null");
            return (Criteria) this;
        }

        public Criteria andIsdelEqualTo(Byte value) {
            addCriterion("isdel =", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotEqualTo(Byte value) {
            addCriterion("isdel <>", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThan(Byte value) {
            addCriterion("isdel >", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThanOrEqualTo(Byte value) {
            addCriterion("isdel >=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThan(Byte value) {
            addCriterion("isdel <", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThanOrEqualTo(Byte value) {
            addCriterion("isdel <=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelIn(List<Byte> values) {
            addCriterion("isdel in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotIn(List<Byte> values) {
            addCriterion("isdel not in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelBetween(Byte value1, Byte value2) {
            addCriterion("isdel between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotBetween(Byte value1, Byte value2) {
            addCriterion("isdel not between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNull() {
            addCriterion("mod_time is null");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNotNull() {
            addCriterion("mod_time is not null");
            return (Criteria) this;
        }

        public Criteria andModTimeEqualTo(Date value) {
            addCriterion("mod_time =", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotEqualTo(Date value) {
            addCriterion("mod_time <>", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThan(Date value) {
            addCriterion("mod_time >", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mod_time >=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThan(Date value) {
            addCriterion("mod_time <", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThanOrEqualTo(Date value) {
            addCriterion("mod_time <=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIn(List<Date> values) {
            addCriterion("mod_time in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotIn(List<Date> values) {
            addCriterion("mod_time not in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeBetween(Date value1, Date value2) {
            addCriterion("mod_time between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotBetween(Date value1, Date value2) {
            addCriterion("mod_time not between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(Byte value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(Byte value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(Byte value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(Byte value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Byte value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<Byte> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<Byte> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(Byte value1, Byte value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdIsNull() {
            addCriterion("audit_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdIsNotNull() {
            addCriterion("audit_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdEqualTo(Long value) {
            addCriterion("audit_user_id =", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdNotEqualTo(Long value) {
            addCriterion("audit_user_id <>", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdGreaterThan(Long value) {
            addCriterion("audit_user_id >", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("audit_user_id >=", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdLessThan(Long value) {
            addCriterion("audit_user_id <", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdLessThanOrEqualTo(Long value) {
            addCriterion("audit_user_id <=", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdIn(List<Long> values) {
            addCriterion("audit_user_id in", values, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdNotIn(List<Long> values) {
            addCriterion("audit_user_id not in", values, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdBetween(Long value1, Long value2) {
            addCriterion("audit_user_id between", value1, value2, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdNotBetween(Long value1, Long value2) {
            addCriterion("audit_user_id not between", value1, value2, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("audit_time is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("audit_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Date value) {
            addCriterion("audit_time =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Date value) {
            addCriterion("audit_time <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Date value) {
            addCriterion("audit_time >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("audit_time >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Date value) {
            addCriterion("audit_time <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("audit_time <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Date> values) {
            addCriterion("audit_time in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Date> values) {
            addCriterion("audit_time not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Date value1, Date value2) {
            addCriterion("audit_time between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("audit_time not between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andRsnidIsNull() {
            addCriterion("rsnid is null");
            return (Criteria) this;
        }

        public Criteria andRsnidIsNotNull() {
            addCriterion("rsnid is not null");
            return (Criteria) this;
        }

        public Criteria andRsnidEqualTo(Long value) {
            addCriterion("rsnid =", value, "rsnid");
            return (Criteria) this;
        }

        public Criteria andRsnidNotEqualTo(Long value) {
            addCriterion("rsnid <>", value, "rsnid");
            return (Criteria) this;
        }

        public Criteria andRsnidGreaterThan(Long value) {
            addCriterion("rsnid >", value, "rsnid");
            return (Criteria) this;
        }

        public Criteria andRsnidGreaterThanOrEqualTo(Long value) {
            addCriterion("rsnid >=", value, "rsnid");
            return (Criteria) this;
        }

        public Criteria andRsnidLessThan(Long value) {
            addCriterion("rsnid <", value, "rsnid");
            return (Criteria) this;
        }

        public Criteria andRsnidLessThanOrEqualTo(Long value) {
            addCriterion("rsnid <=", value, "rsnid");
            return (Criteria) this;
        }

        public Criteria andRsnidIn(List<Long> values) {
            addCriterion("rsnid in", values, "rsnid");
            return (Criteria) this;
        }

        public Criteria andRsnidNotIn(List<Long> values) {
            addCriterion("rsnid not in", values, "rsnid");
            return (Criteria) this;
        }

        public Criteria andRsnidBetween(Long value1, Long value2) {
            addCriterion("rsnid between", value1, value2, "rsnid");
            return (Criteria) this;
        }

        public Criteria andRsnidNotBetween(Long value1, Long value2) {
            addCriterion("rsnid not between", value1, value2, "rsnid");
            return (Criteria) this;
        }

        public Criteria andReasonTextIsNull() {
            addCriterion("reason_text is null");
            return (Criteria) this;
        }

        public Criteria andReasonTextIsNotNull() {
            addCriterion("reason_text is not null");
            return (Criteria) this;
        }

        public Criteria andReasonTextEqualTo(String value) {
            addCriterion("reason_text =", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextNotEqualTo(String value) {
            addCriterion("reason_text <>", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextGreaterThan(String value) {
            addCriterion("reason_text >", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextGreaterThanOrEqualTo(String value) {
            addCriterion("reason_text >=", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextLessThan(String value) {
            addCriterion("reason_text <", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextLessThanOrEqualTo(String value) {
            addCriterion("reason_text <=", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextLike(String value) {
            addCriterion("reason_text like", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextNotLike(String value) {
            addCriterion("reason_text not like", value, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextIn(List<String> values) {
            addCriterion("reason_text in", values, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextNotIn(List<String> values) {
            addCriterion("reason_text not in", values, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextBetween(String value1, String value2) {
            addCriterion("reason_text between", value1, value2, "reasonText");
            return (Criteria) this;
        }

        public Criteria andReasonTextNotBetween(String value1, String value2) {
            addCriterion("reason_text not between", value1, value2, "reasonText");
            return (Criteria) this;
        }

        public Criteria andRobotStatusIsNull() {
            addCriterion("robot_status is null");
            return (Criteria) this;
        }

        public Criteria andRobotStatusIsNotNull() {
            addCriterion("robot_status is not null");
            return (Criteria) this;
        }

        public Criteria andRobotStatusEqualTo(Byte value) {
            addCriterion("robot_status =", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusNotEqualTo(Byte value) {
            addCriterion("robot_status <>", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusGreaterThan(Byte value) {
            addCriterion("robot_status >", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("robot_status >=", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusLessThan(Byte value) {
            addCriterion("robot_status <", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusLessThanOrEqualTo(Byte value) {
            addCriterion("robot_status <=", value, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusIn(List<Byte> values) {
            addCriterion("robot_status in", values, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusNotIn(List<Byte> values) {
            addCriterion("robot_status not in", values, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusBetween(Byte value1, Byte value2) {
            addCriterion("robot_status between", value1, value2, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("robot_status not between", value1, value2, "robotStatus");
            return (Criteria) this;
        }

        public Criteria andRobotReasonIsNull() {
            addCriterion("robot_reason is null");
            return (Criteria) this;
        }

        public Criteria andRobotReasonIsNotNull() {
            addCriterion("robot_reason is not null");
            return (Criteria) this;
        }

        public Criteria andRobotReasonEqualTo(String value) {
            addCriterion("robot_reason =", value, "robotReason");
            return (Criteria) this;
        }

        public Criteria andRobotReasonNotEqualTo(String value) {
            addCriterion("robot_reason <>", value, "robotReason");
            return (Criteria) this;
        }

        public Criteria andRobotReasonGreaterThan(String value) {
            addCriterion("robot_reason >", value, "robotReason");
            return (Criteria) this;
        }

        public Criteria andRobotReasonGreaterThanOrEqualTo(String value) {
            addCriterion("robot_reason >=", value, "robotReason");
            return (Criteria) this;
        }

        public Criteria andRobotReasonLessThan(String value) {
            addCriterion("robot_reason <", value, "robotReason");
            return (Criteria) this;
        }

        public Criteria andRobotReasonLessThanOrEqualTo(String value) {
            addCriterion("robot_reason <=", value, "robotReason");
            return (Criteria) this;
        }

        public Criteria andRobotReasonLike(String value) {
            addCriterion("robot_reason like", value, "robotReason");
            return (Criteria) this;
        }

        public Criteria andRobotReasonNotLike(String value) {
            addCriterion("robot_reason not like", value, "robotReason");
            return (Criteria) this;
        }

        public Criteria andRobotReasonIn(List<String> values) {
            addCriterion("robot_reason in", values, "robotReason");
            return (Criteria) this;
        }

        public Criteria andRobotReasonNotIn(List<String> values) {
            addCriterion("robot_reason not in", values, "robotReason");
            return (Criteria) this;
        }

        public Criteria andRobotReasonBetween(String value1, String value2) {
            addCriterion("robot_reason between", value1, value2, "robotReason");
            return (Criteria) this;
        }

        public Criteria andRobotReasonNotBetween(String value1, String value2) {
            addCriterion("robot_reason not between", value1, value2, "robotReason");
            return (Criteria) this;
        }

        public Criteria andUploadStatusIsNull() {
            addCriterion("upload_status is null");
            return (Criteria) this;
        }

        public Criteria andUploadStatusIsNotNull() {
            addCriterion("upload_status is not null");
            return (Criteria) this;
        }

        public Criteria andUploadStatusEqualTo(Byte value) {
            addCriterion("upload_status =", value, "uploadStatus");
            return (Criteria) this;
        }

        public Criteria andUploadStatusNotEqualTo(Byte value) {
            addCriterion("upload_status <>", value, "uploadStatus");
            return (Criteria) this;
        }

        public Criteria andUploadStatusGreaterThan(Byte value) {
            addCriterion("upload_status >", value, "uploadStatus");
            return (Criteria) this;
        }

        public Criteria andUploadStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("upload_status >=", value, "uploadStatus");
            return (Criteria) this;
        }

        public Criteria andUploadStatusLessThan(Byte value) {
            addCriterion("upload_status <", value, "uploadStatus");
            return (Criteria) this;
        }

        public Criteria andUploadStatusLessThanOrEqualTo(Byte value) {
            addCriterion("upload_status <=", value, "uploadStatus");
            return (Criteria) this;
        }

        public Criteria andUploadStatusIn(List<Byte> values) {
            addCriterion("upload_status in", values, "uploadStatus");
            return (Criteria) this;
        }

        public Criteria andUploadStatusNotIn(List<Byte> values) {
            addCriterion("upload_status not in", values, "uploadStatus");
            return (Criteria) this;
        }

        public Criteria andUploadStatusBetween(Byte value1, Byte value2) {
            addCriterion("upload_status between", value1, value2, "uploadStatus");
            return (Criteria) this;
        }

        public Criteria andUploadStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("upload_status not between", value1, value2, "uploadStatus");
            return (Criteria) this;
        }

        public Criteria andUploadIdIsNull() {
            addCriterion("upload_id is null");
            return (Criteria) this;
        }

        public Criteria andUploadIdIsNotNull() {
            addCriterion("upload_id is not null");
            return (Criteria) this;
        }

        public Criteria andUploadIdEqualTo(String value) {
            addCriterion("upload_id =", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdNotEqualTo(String value) {
            addCriterion("upload_id <>", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdGreaterThan(String value) {
            addCriterion("upload_id >", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdGreaterThanOrEqualTo(String value) {
            addCriterion("upload_id >=", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdLessThan(String value) {
            addCriterion("upload_id <", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdLessThanOrEqualTo(String value) {
            addCriterion("upload_id <=", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdLike(String value) {
            addCriterion("upload_id like", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdNotLike(String value) {
            addCriterion("upload_id not like", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdIn(List<String> values) {
            addCriterion("upload_id in", values, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdNotIn(List<String> values) {
            addCriterion("upload_id not in", values, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdBetween(String value1, String value2) {
            addCriterion("upload_id between", value1, value2, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdNotBetween(String value1, String value2) {
            addCriterion("upload_id not between", value1, value2, "uploadId");
            return (Criteria) this;
        }

        public Criteria andOuterUrlIsNull() {
            addCriterion("outer_url is null");
            return (Criteria) this;
        }

        public Criteria andOuterUrlIsNotNull() {
            addCriterion("outer_url is not null");
            return (Criteria) this;
        }

        public Criteria andOuterUrlEqualTo(String value) {
            addCriterion("outer_url =", value, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andOuterUrlNotEqualTo(String value) {
            addCriterion("outer_url <>", value, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andOuterUrlGreaterThan(String value) {
            addCriterion("outer_url >", value, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andOuterUrlGreaterThanOrEqualTo(String value) {
            addCriterion("outer_url >=", value, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andOuterUrlLessThan(String value) {
            addCriterion("outer_url <", value, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andOuterUrlLessThanOrEqualTo(String value) {
            addCriterion("outer_url <=", value, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andOuterUrlLike(String value) {
            addCriterion("outer_url like", value, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andOuterUrlNotLike(String value) {
            addCriterion("outer_url not like", value, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andOuterUrlIn(List<String> values) {
            addCriterion("outer_url in", values, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andOuterUrlNotIn(List<String> values) {
            addCriterion("outer_url not in", values, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andOuterUrlBetween(String value1, String value2) {
            addCriterion("outer_url between", value1, value2, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andOuterUrlNotBetween(String value1, String value2) {
            addCriterion("outer_url not between", value1, value2, "outerUrl");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVideoCodecIsNull() {
            addCriterion("video_codec is null");
            return (Criteria) this;
        }

        public Criteria andVideoCodecIsNotNull() {
            addCriterion("video_codec is not null");
            return (Criteria) this;
        }

        public Criteria andVideoCodecEqualTo(String value) {
            addCriterion("video_codec =", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecNotEqualTo(String value) {
            addCriterion("video_codec <>", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecGreaterThan(String value) {
            addCriterion("video_codec >", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecGreaterThanOrEqualTo(String value) {
            addCriterion("video_codec >=", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecLessThan(String value) {
            addCriterion("video_codec <", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecLessThanOrEqualTo(String value) {
            addCriterion("video_codec <=", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecLike(String value) {
            addCriterion("video_codec like", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecNotLike(String value) {
            addCriterion("video_codec not like", value, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecIn(List<String> values) {
            addCriterion("video_codec in", values, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecNotIn(List<String> values) {
            addCriterion("video_codec not in", values, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecBetween(String value1, String value2) {
            addCriterion("video_codec between", value1, value2, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andVideoCodecNotBetween(String value1, String value2) {
            addCriterion("video_codec not between", value1, value2, "videoCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecIsNull() {
            addCriterion("audio_codec is null");
            return (Criteria) this;
        }

        public Criteria andAudioCodecIsNotNull() {
            addCriterion("audio_codec is not null");
            return (Criteria) this;
        }

        public Criteria andAudioCodecEqualTo(String value) {
            addCriterion("audio_codec =", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecNotEqualTo(String value) {
            addCriterion("audio_codec <>", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecGreaterThan(String value) {
            addCriterion("audio_codec >", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecGreaterThanOrEqualTo(String value) {
            addCriterion("audio_codec >=", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecLessThan(String value) {
            addCriterion("audio_codec <", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecLessThanOrEqualTo(String value) {
            addCriterion("audio_codec <=", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecLike(String value) {
            addCriterion("audio_codec like", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecNotLike(String value) {
            addCriterion("audio_codec not like", value, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecIn(List<String> values) {
            addCriterion("audio_codec in", values, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecNotIn(List<String> values) {
            addCriterion("audio_codec not in", values, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecBetween(String value1, String value2) {
            addCriterion("audio_codec between", value1, value2, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andAudioCodecNotBetween(String value1, String value2) {
            addCriterion("audio_codec not between", value1, value2, "audioCodec");
            return (Criteria) this;
        }

        public Criteria andVideoRateIsNull() {
            addCriterion("video_rate is null");
            return (Criteria) this;
        }

        public Criteria andVideoRateIsNotNull() {
            addCriterion("video_rate is not null");
            return (Criteria) this;
        }

        public Criteria andVideoRateEqualTo(Double value) {
            addCriterion("video_rate =", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateNotEqualTo(Double value) {
            addCriterion("video_rate <>", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateGreaterThan(Double value) {
            addCriterion("video_rate >", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateGreaterThanOrEqualTo(Double value) {
            addCriterion("video_rate >=", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateLessThan(Double value) {
            addCriterion("video_rate <", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateLessThanOrEqualTo(Double value) {
            addCriterion("video_rate <=", value, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateIn(List<Double> values) {
            addCriterion("video_rate in", values, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateNotIn(List<Double> values) {
            addCriterion("video_rate not in", values, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateBetween(Double value1, Double value2) {
            addCriterion("video_rate between", value1, value2, "videoRate");
            return (Criteria) this;
        }

        public Criteria andVideoRateNotBetween(Double value1, Double value2) {
            addCriterion("video_rate not between", value1, value2, "videoRate");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlIsNull() {
            addCriterion("preview_url is null");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlIsNotNull() {
            addCriterion("preview_url is not null");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlEqualTo(String value) {
            addCriterion("preview_url =", value, "previewUrl");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlNotEqualTo(String value) {
            addCriterion("preview_url <>", value, "previewUrl");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlGreaterThan(String value) {
            addCriterion("preview_url >", value, "previewUrl");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlGreaterThanOrEqualTo(String value) {
            addCriterion("preview_url >=", value, "previewUrl");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlLessThan(String value) {
            addCriterion("preview_url <", value, "previewUrl");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlLessThanOrEqualTo(String value) {
            addCriterion("preview_url <=", value, "previewUrl");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlLike(String value) {
            addCriterion("preview_url like", value, "previewUrl");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlNotLike(String value) {
            addCriterion("preview_url not like", value, "previewUrl");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlIn(List<String> values) {
            addCriterion("preview_url in", values, "previewUrl");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlNotIn(List<String> values) {
            addCriterion("preview_url not in", values, "previewUrl");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlBetween(String value1, String value2) {
            addCriterion("preview_url between", value1, value2, "previewUrl");
            return (Criteria) this;
        }

        public Criteria andPreviewUrlNotBetween(String value1, String value2) {
            addCriterion("preview_url not between", value1, value2, "previewUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}